module.exports = Object.freeze({
    dropDownConstants: {
        religions: [{key: 'rel', text: '-', value: 'rel'}],
        tribes: [{key: 'tri', text: '-', value: 'tri'}],
        maritals: [{key: 'mar', text: '-', value: 'mar'}],
        salutations: [{key: 'sal', text: '-', value: 'sal'}],
        homeCounties: [{key: 'cou', text: '-', value: 'cou'}],
        homeSubCounties: [{key: 'subh', text: '-', value: 'subh'}],
        homeWards: [{key: 'couh', text: '-', value: 'warh'}],
        residentCounties: [{key: 'resc', text: '-', value: 'resc'}],
        residentSubCounties: [{key: 'ressub', text: '-', value: 'ressub'}],
        residentWards: [{key: 'wardres', text: '-', value: 'wardres'}],
    },
    personalInfoFields: [
        {field: 'salutation'},
        {field: 'firstName'},
        {field: 'middleName'},
        {field: 'lastName'},
        {field: 'gender'},
        {field: 'dateOfBirth'},
        {field: 'nationalID'},
        {field: 'maritalStatus'},
        {field: 'ethnicity'},
        {field: 'disabled'},
        {field: 'religion'},
        {field: 'postalAddress'},
        {field: 'postalCode'},
        {field: 'emailAddress'},
        {field: 'mobileNumber'},
        {field: 'homeCounty'},
        {field: 'homeSubCounty'},
        {field: 'homeWard'},
        {field: 'countyOfResidence'},
        {field: 'subCountyOfResidence'},
        {field: 'countyOfResidenceWard'},
    ],
    academicValuesFields: [
        {field: 'secondarySchoolName'},
        {field: 'secondarySchoolYearOfCompletion'},
        {field: 'secondaryOverallGrade'},
        {field: 'mathGrade'},
        {field: 'englishGrade'},
        {field: 'kiswahiliGrade'},
        {field: 'biologyGrade'},
        {field: 'physicsGrade'},
        {field: 'chemistryGrade'}
    ],
    postSecondaryValuesFields: [
        {field: 'schoolName'},
        {field: 'start'},
        {field: 'end'},
        {field: 'courseName'},
        {field: 'educationLevel'},
     ],
    experienceValuesFields: [
        {field: 'companyName'},
        {field: 'jobTitle'},
        {field: 'currentActive'},
        {field: 'startDate'},
        {field: 'endDate'},
        {field: 'description'},
     ],coverLetterFields: [
        {field: 'coverLetter'},
        {field: 'kraClearace'},
        {field: 'helbClearance'},
        {field: 'eaccClearance'},
        {field: 'crbClearance'},
        {field: 'goodConductClearance'},
     ],
})
;