module.exports = Object.freeze({

    personalInfoFields: [
        {field: 'salutation', index: 0},
        {field: 'firstName', index: 1},
        {field: 'middleName', index: 2},
        {field: 'lastName', index: 3},
        {field: 'gender', index: 4},
        {field: 'dateOfBirth', index: 5},
        {field: 'nationalID', index: 6},
        {field: 'maritalStatus', index: 7},
        {field: 'ethnicity', index: 8},
        {field: 'disabled', index: 9},
        {field: 'religion', index: 10},
        {field: 'postalAddress', index: 11},
        {field: 'postalCode', index: 12},
        {field: 'emailAddress', index: 13},
        {field: 'mobileNumber', index: 14},
    ],
    personalCountyFields: [
        {field: 'homeCounty', index: 0},
        {field: 'homeSubCounty', index: 0},
        {field: 'homeWard', index: 0},
        {field: 'countyOfResidence', index: 0},
        {field: 'subCountyOfResidence', index: 0},
        {field: 'countyOfResidenceWard', index: 0},
    ],
    academicValuesFields: [
        {field: 'secondarySchoolName', index: 0},
        {field: 'secondarySchoolYearOfCompletion', index: 1},
        {field: 'secondaryOverallGrade', index: 2},
        {field: 'mathGrade', index: 3},
        {field: 'englishGrade', index: 4},
        {field: 'kiswahiliGrade', index: 5},
        {field: 'biologyGrade', index: 6},
        {field: 'physicsGrade', index: 7},
        {field: 'chemistryGrade', index: 7}
    ],
    postSecondaryValuesFields: [
        {field: 'schoolName', index: 0},
        {field: 'start', index: 0},
        {field: 'end', index: 0},
        {field: 'courseName', index: 0},
        {field: 'educationLevel', index: 0},
    ],
    experienceValuesFields: [
        {field: 'companyName', index: 0},
        {field: 'jobTitle', index: 0},
        {field: 'currentActive', index: 0},
        {field: 'startDate', index: 0},
        {field: 'endDate', index: 0},
        {field: 'description', index: 0},
    ],
});